---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.11
  amd64: ghcr.io/home-assistant/amd64-base:3.11
  armhf: ghcr.io/home-assistant/armhf-base:3.11
  armv7: ghcr.io/home-assistant/armv7-base:3.11
  i386: ghcr.io/home-assistant/i386-base:3.11

