build_from:
  aarch64: ghcr.io/hassio-addons/base:latest
  amd64: ghcr.io/hassio-addons/base:latest
  armhf: ghcr.io/hassio-addons/base:latest
  armv7: ghcr.io/hassio-addons/base:latest
  i386: ghcr.io/hassio-addons/base:latest
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev