---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:12.2.7
  amd64: ghcr.io/home-assistant/amd64-base:12.2.7
  armhf: ghcr.io/home-assistant/armhf-base:12.2.7
  armv7: ghcr.io/home-assistant/armv7-base:12.2.7
  i386: ghcr.io/home-assistant/i386-base:12.2.7

