name: "Publish"

on:
  release:
    types: [published]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_ARGS: ${{needs.variables.outputs.DOCKER_ARGS}}
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]
        addon: [tunnel]
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      uses: home-assistant/builder@master
      with:
          args: |
            --${{ matrix.arch }} \
            --target ${{ matrix.addon }} \
            --docker-hub imdgr
