name: "Publish"

on:
  release:
    types: [published]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_ARGS: ${{needs.variables.outputs.DOCKER_ARGS}}
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]
        addon: [tunnel]
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        docker run --rm --privileged \
            -v /home/runner/.docker:/root/.docker \
            -v /run/docker.sock:/run/docker.sock:rw \
            -v $(pwd)/${{ matrix.addon }}:/data homeassistant/amd64-builder --${{ matrix.arch }} -t /data \
            ${{ env.DOCKER_ARGS }}
